POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "Comprar leite",
  "description": "Comprar leite integral no mercado.",
  "completed": false
}


###

GET http://localhost:3000/todos?search=leite


###

PUT http://localhost:3000/todos/3153f61f-d70e-4823-8e37-8e93aca02f40
Content-Type: application/json

{
  "title": "Comprar leite",
  "description": "Comprar leite integral no mercado.",
  "completed": true
}


###

DELETE http://localhost:3000/tods/a44f3f71-a59b-451a-a4e0-762f12246f6a
